default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: UTF8
  host: 127.0.0.1
  port: 5432
  username: nurasyl
  password: 12345
  database: seven_note

development:
  <<: *default
  database: seven_note_dev

test:
  <<: *default
  database: seven_note_test

production:
  <<: *default
